#!/bin/bash

set -e

# install pyenv
if [ ! -d ~/.pyenv ]; then
    curl https://pyenv.run | bash
fi

# install python build dependencies
sudo apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
                 libsqlite3-dev tk-dev libgdbm-dev libc6-dev \
                 libbz2-dev

# install python 3.6 and set as local
#pyenv install 3.6.8
#pyenv local 3.6.8

# install poetry
#curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

# install python dependencies
#poetry install

# build so that we can generate a setup.py for installing as a development package
poetry build
VERSION=$(poetry run python -c "from openapi_conformance import __version__; print(__version__, end='')")
tar -zxvf dist/openapi_conformance-$VERSION.tar.gz openapi_conformance-$VERSION/setup.py
mv openapi_conformance-$VERSION/setup.py .
rm -rf openapi_conformance-$VERSION
poetry run pip install -e .
rm setup.py
