#!/bin/bash

set -e

poetry run isort -rc --check-only -q
poetry run black . --check --quiet
poetry run pylama
poetry run mypy -m openapi_conformance --ignore-missing-imports
poetry run vulture openapi_conformance --min-confidence 100
poetry run safety check --bare